apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-redis-data
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-redis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3-encrypted
  resources:
    requests:
      storage: 1Gi
